version: '3.8'

services:
  # 1. Сервис PostgreSQL
  postgres:
    image: postgres:17
    container_name: some-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zero42
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#2 FastAPI приложение
web:
  build: .
  container_name: onlinechat-api 
  ports:
    - "8000:8000"
  environment:
    DATABASE_URL: postgres://postgres:zero42@postgres:5432/postgres
  volumes:
    - .:/app
  depends_on:
    postgres:
      condition: sevices_healthy
  command: >
    sh -c "alembic upgrade head &&
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

          